name: depremapp
description: Provides access to last minute earthquakes in Turkey.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  #State Management
  get: ^4.6.5

  #Firebase
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  firebase_analytics: ^9.1.9
  firebase_core_platform_interface: ^4.5.1

  #Maps
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

  #Network
  intl: ^0.17.0
  http: ^1.0.0

  #UI Operations
  lottie: ^1.4.1
  flutter_screenutil: ^5.5.3+2
  kartal: ^3.5.0
  easy_logger: ^0.0.2
  logger: ^2.0.2+1

  #Other
  cupertino_icons: ^1.0.2


dev_dependencies:
  very_good_analysis: ^5.1.0 


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

